### ISSUE TITLE
Analyze and Plan updates

### ISSUE THREAD

**Issue by NuwanJ** [cepdnaclk/web#7]
- [Summary of the survey](https://docs.google.com/document/d/19DyE5blPCw7S6iCe1-UksKEs8Z7QTt4ursZyYUrrQyg/edit?usp=sharing)

### TODO
- [ ] Organize the research groups and collect content
- [ ] Content writing for pages
- [ ] Consider new feature requests 
   - [ ] Detailed course pages 
   - [ ] Department floor plan
   - [ ] ... 
- [ ] Maintenance plan with roles and responsibilities
